# Generated by Django 3.0 on 2021-08-06 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangoyearlessdate.models
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('author', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('publication_date', partial_date.fields.PartialDateField(blank=True, default=None, help_text='YYYY or YYYY-MM or YYYY-MM-DD', null=True)),
                ('journal', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('book', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('volume', models.IntegerField(blank=True, default=None, null=True)),
                ('issue', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('conference', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('page', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('publisher', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('total_citations', models.IntegerField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('year', djangoyearlessdate.models.YearField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, max_length=10000, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
