# Generated by Django 3.0 on 2021-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='book',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='conference',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='issue',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
